/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "ADC_in_aliases.h"
#include "ADC_in.h"
#include "LED7_aliases.h"
#include "LED7.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_Master.h"
#include "I2C_Master_PVT.h"
#include "Sample_Timer.h"
#include "Clock_1.h"
#include "Sample_ISR.h"
#include "Solenoid_1_aliases.h"
#include "Solenoid_1.h"
#include "emFile.h"
#include "LED2_aliases.h"
#include "LED2.h"
#include "Countdown_timer.h"
#include "countdown.h"
#include "LED2_1_aliases.h"
#include "LED2_1.h"
#include "adjust_timer.h"
#include "Solenoid_2_aliases.h"
#include "Solenoid_2.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "emFile_SPI0.h"
#include "emFile_SPI0_PVT.h"
#include "emFile_mosi0_aliases.h"
#include "emFile_mosi0.h"
#include "emFile_Clock_1.h"
#include "emFile_miso0_aliases.h"
#include "emFile_miso0.h"
#include "emFile_sclk0_aliases.h"
#include "emFile_sclk0.h"
#include "emFile_SPI0_CS_aliases.h"
#include "emFile_SPI0_CS.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

